### ISSUE TITLE
Stock chart renders without zoom, returns error: TypeError: Cannot set property 'top' of undefined

### ISSUE THREAD

**Issue by romran** [highcharts/highcharts-vue#12] opened 2018-06-11 16:23 UTC
Hello,
I have tried your demo last week and Stock Chart was working as expected, today, after I had to reinstall dependencies it returns error:
```
[Vue warn]: Error in callback for watcher "options": "TypeError: Cannot set property 'top' of undefined" found in
---> <Highcharts>
       <StockChart> at src\components\StockChart.vue
         <App> at src\App.vue
           <Root>
```
and seems that zoom do not work (link to print screen below)

[https://i.gyazo.com/dd0000506fb02393d01bf483f4031c6e.png](https://i.gyazo.com/dd0000506fb02393d01bf483f4031c6e.png)

May you tell, if you are experiencing same error?

**Comment by sebastianbochan** [comment] 2018-06-12 07:42
Hi @romran,
Thank you for reporting. We will debug and fix it as soon as possible.

@Denyllon

**Comment by Denyllon** [comment] 2018-06-12 09:36
hi @romran ,

Duplicate of #10 . Actually, the issue is directly related with Highstock (exactly the `Chart.update()` function and its `oneToOne` flag), not the wrapper. It's already fixed on `master` branch of `highcharts` repository, so before the new version comes out, you can set `updateArgs` of stock chart to `[true, false]`.

`<highcharts class="stock" :constructor-type="'stockChart'" :options="stockOptions" :updateArgs="[true, false]"></highcharts>`

**Closed** 2018-06-12 09:45 UTC
Labels: Duplicate
