### ISSUE TITLE
pointPlacement option not work

### ISSUE THREAD

**Issue by scabezasiq** [highcharts/highcharts-vue#103] opened 2019-08-23 15:22 UTC
Hi, I migrated from vue-highcharts to this library and I can't make it that the chart look like before.

Should look like that:
![Captura de Pantalla 2019-08-23 a la(s) 11 09 59](https://user-images.githubusercontent.com/44446067/63602957-9c539380-c596-11e9-9471-4dd662b876a8.png)

But it look like this:
![Captura de Pantalla 2019-08-23 a la(s) 11 11 18](https://user-images.githubusercontent.com/44446067/63603035-c016d980-c596-11e9-9847-99229dab57ad.png)

This is the example code for reproduce:
[https://github.com/scabezasiq/example-highchart](url)

**Comment by KacperMadej** [comment] 2019-08-28 14:28
Hi @scabezasiq 

Thank you for reporting the problem.

This is probably because you have been using an older version of Highcharts, like 7.0.0, where this worked as you wanted: https://jsfiddle.net/BlackLabel/2Lden3mv/

It looks like a regression (broken since 7.1.0, worked up to 7.0.3) in Highcharts, so I will open an issue in the main Highcharts report and close this one.

As a workaround, you could add `pointRange: 1` for all series. This value should be calculated automatically but isn't for some reason (bug).
Demo: https://jsfiddle.net/BlackLabel/2Lden3mv/1/

You could continue with the issue on the main Highcharts repository here:
https://github.com/highcharts/highcharts/issues/11800

**Closed by KacperMadej** 2019-08-28 14:28 UTC
