### ISSUE TITLE
Options are reset on chart.update

### ISSUE THREAD

**Issue by micahjscheer** [highcharts/highcharts-vue#46] opened 2018-12-18 03:45 UTC
I noticed that after updating to Highcharts 7, nested options (ie. label), were being replaced with an empty object if the computed options object (I was passing as a prop), was updated. I, therefore, drew the conclusion that something on the chart.update was mutating the options deeply.

I noticed that there was an update to highcharts-vue made where you fixed errors on updating, caused by mutating data. I believe a possible solution to this issue could be that instead of using Object.assign to do a shallow clone, a deep clone could be done instead.

**Comment by TorsteinHonsi** [comment] 2018-12-18 14:14
Fixed upstream in https://github.com/highcharts/highcharts/issues/9711

**Comment by KacperMadej** [comment] 2018-12-19 17:43
The problem should be resolved in Highcharts version 7.0.1 - it's already published.
Please reopen in case the problem is not resolved.

**Closed by KacperMadej** 2018-12-19 17:43 UTC
