### ISSUE TITLE
HighMaps - You may have an infinite update loop in watcher with expression "options"

### ISSUE THREAD

**Issue by Eclixal** [highcharts/highcharts-vue#80] opened 2019-05-17 14:58 UTC
Hi,
I want to use HighMaps with the parameter https://api.highcharts.com/highmaps/series.map.allAreas

But when I reload my page I have this error 
![image](https://user-images.githubusercontent.com/28450187/57936718-bbba9080-78c4-11e9-8115-fb2b7e3a236f.png)

And my code 
![image](https://user-images.githubusercontent.com/28450187/57936762-d0972400-78c4-11e9-86ae-7a9b357f0d5b.png)

When I set the value to false it load correctly the page.
I don't understand why it doesn't work...

Thanks

**Comment by Denyllon** [comment] 2019-05-20 13:15
Hello @Eclixal ,

Thank you for reporting the issue.
Could you tell me which version of wrapper have you been running? Would be also much more convenient to see some live example reproduced in [Codesandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/), where the problem is noticeable, so could you provide me with it?

Kind regards!

**Comment by Denyllon** [comment] 2019-05-21 12:57
Meanwhile, I've reproduced the issue on official wrapper demo, and investigated it much deeper. The problem is caused by the fact that Highcharts mutates a component data just from the beginning.
It's definitely the bug, and will be fixed soon, by applying the same way of copying options object, as it is in watch function.

**Closed** 2019-05-21 13:51 UTC
Labels: Bug
