### ISSUE TITLE
Worldmap export to CSV random data

### ISSUE THREAD

**Issue by dcr31000** [highcharts/highcharts-vue#153] opened 2020-06-26 08:39 UTC
Hello,
I tried to export Wordmap data to CSV with Highcharts export data but it's not working fine.

For example, I used your Worldmap demo and added to Chart.vue:
```
import Highcharts from "highcharts";
import Exporting from "highcharts/modules/exporting";
import ExportData from "highcharts/modules/export-data";

Exporting(Highcharts);
ExportData(Highcharts);
```

And the result was:
"Category";"Random data"
"Faroe Islands";0
"United States Minor Outlying Islands";1
"United States of America";2
"Japan";3
"Seychelles";4
[...]

**Comment by dcr31000** [comment] 2020-06-27 08:52
Update: it's working fine on Highcharts 8.1.0 but not working fine since 8.1.1

**Comment by dcr31000** [comment] 2020-06-29 07:49
I reproduced this problem with Highcharts pure JS (without vue) and created an issue in Highcharts Github repository.

**Comment by dcr31000** [comment] 2020-06-29 14:07
Workaround from Highcharts:
Set `xAxis.type = "category"`.

**Comment by pawelfus** [comment] 2020-06-29 14:20
Thanks! Closing as duplicate of https://github.com/highcharts/highcharts/issues/13785

**Closed by pawelfus** 2020-06-29 14:20 UTC
