### ISSUE TITLE
Update map series generate error

### ISSUE THREAD

**Issue by Eclixal** [highcharts/highcharts-vue#89] opened 2019-07-01 12:27 UTC
I want to update the data on a map with this code :

`mapOptions.series[0].data = '[["FR", 22], ["US", 554]]';`

```
mapOptions: {
                    chart: {
                        map: 'myMapName',
                        backgroundColor: '#26374C'
                    },
                    title: {
                        text: ''
                    },
                    mapNavigation: {
                        enabled: true,
                        enableButtons: false
                    },

                    legend:{enabled: false},
                    credits:{enabled:false},
                    exporting:{enabled: false},
                    colorAxis: {
                        min: 0,
                        minColor: 'rgba(0,121,234,0.1)',
                        maxColor: 'rgba(0,121,234,0.9)'
                    },
                    series: [{
                        name: 'Répartition des joueurs',
                        nullColor: '#324967',
                        borderColor: '#2d3d5a',
                        states: {
                            hover: {
                                color: '#0079EA'
                            }
                        },
                        allAreas: true,
                        data: null
                    }]
                }
```

But I have the following error :

![image](https://user-images.githubusercontent.com/28450187/60436468-620bec80-9c0c-11e9-89c9-104dd6981583.png)

**Comment by Denyllon** [comment] 2019-07-02 07:59
Hi @Eclixal 

Thank you for reporting the issue. I'll take a look on that today, and after that get back with response.

Kind regards!

**Comment by Eclixal** [comment] 2019-07-04 10:32
I use axios to get all my data and on success I just 

`mapOptions.series[0].data = '[["FR", 22], ["US", 554]]';`

But he doesn't work

**Comment by Denyllon** [comment] 2019-07-05 10:59
If you assigning it exactly like above, the problem is that the data is String instead of Array. Could you verify it?

**Comment by Eclixal** [comment] 2019-07-05 12:45
Oh yes, I'm stupid ... Its work now

**Closed** 2019-07-05 12:46 UTC
