### ISSUE TITLE
Calling chart.destroy causes error

### ISSUE THREAD

**Issue by ldsenow** [highcharts/highcharts-vue#214] opened 2022-05-13 02:52 UTC
Hi,

it is related to issue https://github.com/highcharts/highcharts/issues/11553 

My comment about the issue, i hope it helps to resolve the error. https://github.com/highcharts/highcharts/issues/11553#issuecomment-1125602415

**Comment by ldsenow** [comment] 2022-05-17 02:36
Is this repo being maintained? Can I do a PR for this or would someone take a look?

**Comment by jakubSzuminski** [comment] 2024-02-05 07:08
Closing as it is a duplicate of this issue: https://github.com/highcharts/highcharts-vue/issues/249

**Closed by jakubSzuminski** 2024-02-05 07:08 UTC
Labels: Bug, Duplicate
