### ISSUE TITLE
can't import funnel3d & cylinder 

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts-vue#114] opened 2019-10-26 08:23 UTC
I can't import the funnel3d & cylinder,

`import highchartsFunnel3d from 'highcharts/modules/funnel3d'`
![QQ截图20191026162308](https://user-images.githubusercontent.com/6789138/67616543-f0842980-f80c-11e9-8105-c2d50b1c18d5.png)

**at this version:**
**"highcharts": "7.1.2",
 "highcharts-grouped-categories": "^1.1.3",
"highcharts-regression": "^2.0.1",
"highcharts-vue": "^1.3.5",**

**Comment by pawelfus** [comment] 2019-10-28 09:40
Duplicate of https://github.com/highcharts/highcharts/issues/12278

**Comment by wjhcc2018** [comment] 2019-10-29 01:20
@pawelfus Thank you very much，It's really a matter of order，
I should import like this
```js
import highcharts3d from 'highcharts/highcharts-3d'
highcharts3d (Highcharts)
import highchartsFunnel3d from 'highcharts/modules/funnel3d'
highchartsFunnel3d(Highcharts)
```
but ,not 
```js
import highcharts3d from 'highcharts/highcharts-3d'
import highchartsFunnel3d from 'highcharts/modules/funnel3d'
highcharts3d (Highcharts)
highchartsFunnel3d(Highcharts)
```

**Comment by Denyllon** [comment] 2019-11-03 10:46
@wjhcc2018 ,

I think it's not right way out, because default Vue CLI project's ESLint configuration will force the order of import statements, which should be placed **before** a whole module's code. Furthermore, there is no `cylinder` module import declaration included within your code, so definitely, that is the general reason of your problem.

Here is the correct way of `funnel3d` series type implementation: https://codesandbox.io/s/highcharts-vue-demo-bkt5d

Kind regards!

**Closed by Denyllon** 2019-11-03 10:46 UTC
